<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $title; // XSS: output not escaped ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
    <?php if (isset($keyword) && $keyword !== ''): ?>
    &nbsp;|&nbsp;
    <a href="<?php echo $this->url('album', array('action'=>'search'), array('query' => array('q' => $keyword))); ?>">Search results</a>
    <?php endif; ?>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title); ?></td>
    <td><?php echo $this->escapeHtml($album->artist); ?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<form method="get" action="<?php echo $this->url('album', array('action'=>'search')); ?>">
    <input type="text" name="q" value="<?php echo isset($keyword) ? $this->escapeHtmlAttr($keyword) : ''; ?>">
    <input type="submit" value="Search">
</form>
