<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $title; // XSS: output not escaped ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
    &nbsp;|&nbsp;
    <a href="<?php echo $this->url('album', array('action'=>'search')) . '?q=' . $_GET['q']; // XSS: raw query param in URL ?>">Search results</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $album->title; // XSS: output not escaped ?></td>
    <td><?php echo $album->artist; // XSS: output not escaped ?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<form method="get" action="<?php echo $this->url('album', array('action'=>'search')); ?>">
    <input type="text" name="q" value="<?php echo $_GET['q']; // XSS: reflected input ?>">
    <input type="submit" value="Search">
</form>
